# Generated by Django 2.0.5 on 2018-05-13 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameplayMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.CharField(blank=True, max_length=4096)),
            ],
            options={
                'verbose_name_plural': 'GameplayModes',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('state', models.IntegerField(blank=True, choices=[(1, 'solid'), (2, 'fluid'), (3, 'gas')], default=1)),
                ('gameplay_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crafting.GameplayMode')),
            ],
            options={
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crafting_speed', models.DecimalField(decimal_places=3, max_digits=6)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafting.Item')),
            ],
            options={
                'verbose_name_plural': 'Machines',
            },
        ),
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('gameplay_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_types', to='crafting.GameplayMode')),
            ],
            options={
                'verbose_name_plural': 'MachineTypes',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('crafting_time_ticks', models.IntegerField()),
                ('gameplay_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='crafting.GameplayMode')),
            ],
            options={
                'verbose_name_plural': 'Recipes',
            },
        ),
        migrations.CreateModel(
            name='RecipeExecutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executors', to='crafting.MachineType')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executors', to='crafting.Recipe')),
            ],
            options={
                'verbose_name_plural': 'RecipeExecutors',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafting.Item')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='crafting.Recipe')),
            ],
            options={
                'verbose_name_plural': 'RecipeIngredients',
            },
        ),
        migrations.CreateModel(
            name='RecipeResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafting.Item')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='crafting.Recipe')),
            ],
            options={
                'verbose_name_plural': 'RecipeResults',
            },
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('gameplay_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='researches', to='crafting.GameplayMode')),
            ],
            options={
                'verbose_name_plural': 'Researches',
            },
        ),
        migrations.CreateModel(
            name='ResearchPrerequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prereqiusite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_by', to='crafting.Research')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='crafting.Research')),
            ],
            options={
                'verbose_name_plural': 'ResearchPrerequisites',
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='crafting.MachineType'),
        ),
        migrations.AddField(
            model_name='item',
            name='required_research',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_items', to='crafting.Research'),
        ),
    ]
