# Generated by Django 2.0.5 on 2018-05-14 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0002_auto_20180513_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='tier',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='recipe',
            name='required_research',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_recipes', to='crafting.Research'),
        ),
        migrations.AddField(
            model_name='recipeexecutor',
            name='machine_tier_required',
            field=models.IntegerField(default=1),
        ),
    ]
