# Generated by Django 2.0.5 on 2018-05-14 08:30

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0003_auto_20180514_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='required_research',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='gameplay_mode', chained_model_field='gameplay_mode', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_items', to='crafting.Research'),
        ),
    ]
