# Generated by Django 2.0.5 on 2018-05-14 09:38

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0005_auto_20180514_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='gameplay_mode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='crafting.GameplayMode'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='item',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='gameplay_mode', chained_model_field='gameplay_mode', on_delete=django.db.models.deletion.CASCADE, to='crafting.Item', unique=True),
        ),
    ]
