# Generated by Django 2.0.5 on 2018-05-14 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0006_auto_20180514_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='gameplay_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='crafting.GameplayMode'),
        ),
    ]
