# Generated by Django 2.0.5 on 2018-05-14 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0007_auto_20180514_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinetype',
            name='gameplay_mode',
        ),
    ]
