# Generated by Django 2.0.5 on 2018-05-14 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0011_auto_20180514_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeexecutor',
            name='gameplay_mode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crafting.GameplayMode'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='gameplay_mode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crafting.GameplayMode'),
        ),
        migrations.AddField(
            model_name='reciperesult',
            name='gameplay_mode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crafting.GameplayMode'),
        ),
    ]
