# Generated by Django 2.0.5 on 2018-05-14 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0014_auto_20180514_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machinetype',
            name='gameplay_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_types', to='crafting.GameplayMode'),
        ),
    ]
