# Generated by Django 2.0.5 on 2018-05-14 10:13

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0015_auto_20180514_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='required_research',
            field=smart_selects.db_fields.ChainedForeignKey(blank=True, chained_field='gameplay_mode', chained_model_field='gameplay_mode', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unlocked_recipes', to='crafting.Research'),
        ),
    ]
