# Generated by Django 2.0.5 on 2018-05-14 10:19

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0016_auto_20180514_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeexecutor',
            name='machine_type',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='gameplay_mode', chained_model_field='gameplay_mode', on_delete=django.db.models.deletion.CASCADE, related_name='executors', to='crafting.MachineType'),
        ),
        migrations.AlterField(
            model_name='recipeexecutor',
            name='recipe',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='gameplay_mode', chained_model_field='gameplay_mode', on_delete=django.db.models.deletion.CASCADE, related_name='executors', to='crafting.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='item',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='gameplay_mode', chained_model_field='gameplay_mode', on_delete=django.db.models.deletion.CASCADE, to='crafting.Item'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='gameplay_mode', chained_model_field='gameplay_mode', on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='crafting.Recipe'),
        ),
        migrations.AlterField(
            model_name='reciperesult',
            name='item',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='gameplay_mode', chained_model_field='gameplay_mode', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_results', to='crafting.Item'),
        ),
        migrations.AlterField(
            model_name='reciperesult',
            name='recipe',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='gameplay_mode', chained_model_field='gameplay_mode', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='crafting.Recipe'),
        ),
    ]
