# Generated by Django 2.0.5 on 2018-05-14 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0017_auto_20180514_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchprerequisite',
            name='gameplay_mode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crafting.GameplayMode'),
        ),
    ]
