# Generated by Django 2.0.5 on 2018-05-14 10:42

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0019_auto_20180514_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researchprerequisite',
            name='research',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='gameplay_mode', chained_model_field='gameplay_mode', on_delete=django.db.models.deletion.CASCADE, related_name='prerequisites', to='crafting.Research'),
        ),
    ]
