# Generated by Django 2.0.5 on 2018-05-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0020_auto_20180514_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researchprerequisite',
            old_name='prereqiusite',
            new_name='prerequisite',
        ),
    ]
