# Generated by Django 2.0.5 on 2018-05-14 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0021_auto_20180514_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='power_usage_kW',
            field=models.IntegerField(default=0),
        ),
    ]
