# Generated by Django 2.0.5 on 2018-05-14 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
        ('crafting', '0022_machine_power_usage_kw'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplaymode',
            name='editing_groups',
            field=models.ManyToManyField(related_name='gameplay_modes', to='auth.Group'),
        ),
        migrations.AddField(
            model_name='gameplaymode',
            name='editing_users',
            field=models.ManyToManyField(related_name='gameplay_modes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameplaymode',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
