# Generated by Django 2.0.5 on 2018-05-16 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0023_auto_20180515_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='FiniteResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mining_hardness', models.DecimalField(decimal_places=3, max_digits=6)),
                ('mining_time', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
            options={
                'verbose_name_plural': 'FiniteResources',
            },
        ),
        migrations.CreateModel(
            name='FiniteResourceCollectionIngredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'FiniteResourceCollectionIngredients',
            },
        ),
        migrations.CreateModel(
            name='FiniteResourceCollector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mining_power', models.DecimalField(decimal_places=3, max_digits=6)),
                ('mining_speed', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
            options={
                'verbose_name_plural': 'FiniteResourceCollectors',
            },
        ),
        migrations.CreateModel(
            name='FiniteResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'FiniteResourceTypes',
            },
        ),
        migrations.AlterField(
            model_name='gameplaymode',
            name='editing_groups',
            field=models.ManyToManyField(blank=True, related_name='gameplay_modes', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='gameplaymode',
            name='editing_users',
            field=models.ManyToManyField(blank=True, related_name='gameplay_modes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finiteresourcetype',
            name='gameplay_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finite_resource_types', to='crafting.GameplayMode'),
        ),
        migrations.AddField(
            model_name='finiteresourcecollector',
            name='finite_resource_type',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='gameplay_mode', chained_model_field='gameplay_mode', on_delete=django.db.models.deletion.CASCADE, related_name='finite_resource_collectors', to='crafting.FiniteResourceType'),
        ),
        migrations.AddField(
            model_name='finiteresourcecollector',
            name='gameplay_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resource_collectors', to='crafting.GameplayMode'),
        ),
        migrations.AddField(
            model_name='finiteresourcecollector',
            name='item',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='gameplay_mode', chained_model_field='gameplay_mode', on_delete=django.db.models.deletion.CASCADE, to='crafting.Item', unique=True),
        ),
        migrations.AddField(
            model_name='finiteresourcecollectioningredient',
            name='gameplay_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crafting.GameplayMode'),
        ),
        migrations.AddField(
            model_name='finiteresourcecollectioningredient',
            name='item',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='gameplay_mode', chained_model_field='gameplay_mode', on_delete=django.db.models.deletion.CASCADE, to='crafting.Item'),
        ),
        migrations.AddField(
            model_name='finiteresourcecollectioningredient',
            name='resource',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='gameplay_mode', chained_model_field='gameplay_mode', on_delete=django.db.models.deletion.CASCADE, related_name='collection_ingredients', to='crafting.FiniteResource'),
        ),
        migrations.AddField(
            model_name='finiteresource',
            name='finite_resource_type',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='gameplay_mode', chained_model_field='gameplay_mode', on_delete=django.db.models.deletion.CASCADE, related_name='finite_resources', to='crafting.FiniteResourceType'),
        ),
        migrations.AddField(
            model_name='finiteresource',
            name='gameplay_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finite_resources', to='crafting.GameplayMode'),
        ),
        migrations.AddField(
            model_name='finiteresource',
            name='item',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='gameplay_mode', chained_model_field='gameplay_mode', on_delete=django.db.models.deletion.CASCADE, to='crafting.Item', unique=True),
        ),
    ]
