# Generated by Django 2.0.5 on 2018-05-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0024_auto_20180516_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='finiteresourcecollector',
            name='power_usage_kW',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='finiteresourcecollector',
            name='tier',
            field=models.IntegerField(default=1),
        ),
    ]
