# Generated by Django 2.0.5 on 2018-05-31 13:13

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('crafting', '0027_remove_gameplaymode_editing_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='item',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='gameplay_mode', chained_model_field='gameplay_mode', on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='crafting.Item'),
        ),
    ]
