from .expression import *
from .parser import *

expression_lookup_tables = [
    # 0D
    [],

    # 1D
    [
        Constant(True),
        Constant(False)
    ],

    # 2D
    [
        Constant(False),
        parse_expression('!a&!b'),
        parse_expression('a&!b'),
        parse_expression('!b'),
        parse_expression('!a&b'),
        parse_expression('!a'),
        parse_expression('a^b'),
        parse_expression('!(a&b)'),
        parse_expression('a&b'),
        parse_expression('a=b'),
        parse_expression('a'),
        parse_expression('b>a'),
        parse_expression('b'),
        parse_expression('a>b'),
        parse_expression('a|b'),
        Constant(True)
    ],

    # 3D
    [
        Constant(False),
        parse_expression('!(a|b|c)'),
        parse_expression('a&!(b|c)'),
        parse_expression('!(c|b)'),
        parse_expression('!(a|c)&b'),
        parse_expression('!(a|c)'),
        parse_expression('!c&(a^b)'),
        parse_expression('!((b&a)|c)'),
        parse_expression('a&b&!c'),
        parse_expression('(a=b)&!c'),
        parse_expression('a&!c'),
        parse_expression('(b>a)&!c'),
        parse_expression('b&!c'),
        parse_expression('(a>b)&!c'),
        parse_expression('(a|b)&!c'),
        parse_expression('!c'),
        parse_expression('!(a|b)&c'),
        parse_expression('!(a|b)'),
        parse_expression('!b&(a^c)'),
        parse_expression('!((a&c)|b)'),
        parse_expression('!a&(b^c)'),
        parse_expression('!((b&c)|a)'),
        parse_expression('a^b^c^(a&b&c)'),
        parse_expression('!((a&(b|c))|(b&c))'),
        parse_expression('(a^c)&(b^c)'),
        parse_expression('(c=>!b)&(a<=>b)'),
        parse_expression('(c^a)&(b=>a)'),
        parse_expression('a|b=>a&!c'),
        parse_expression('(c^b)&(a=>b)'),
        parse_expression('!(b&c)&(a=>b)'),
        parse_expression('c^(b|a)'),
        parse_expression('!((b|a)&c)'),
        parse_expression('a&!b&c'),
        parse_expression('!b&(c<=>a)'),
        parse_expression('a&!b'),
        parse_expression('!b&(c=>a)'),
        parse_expression('(b^c)&(b^a)'),
        parse_expression('(c<=>a)&(a=>!b)'),
        parse_expression('(a^b)&(c=>a)'),
        parse_expression('a|c=>!b&a'),
        parse_expression('(b^c)&a'),
        parse_expression('c^b<=>a|(c&b)'),
        parse_expression('a&(c=>!b)'),
        parse_expression('(c|b=>a)&!(b&c)'),
        parse_expression('(c^b)&(c=>a)'),
        parse_expression('!((a=>b)<=>c)'),
        parse_expression('(b|a)&(b=>!c)'),
        parse_expression('c=>a&!b'),
        parse_expression('!b&c'),
        parse_expression('(a>c)&!b'),
        parse_expression('(a|c)&!b'),
        parse_expression('!b'),
        parse_expression('(b^c)&(a=>c)'),
        parse_expression('a|c=>!b&c'),
        parse_expression('(c|a)^b'),
        parse_expression('b=>!(a|c)'),
        parse_expression('(a|c)&(c^b)'),
        parse_expression('!((a=>c)<=>b)'),
        parse_expression('(c|a)&!(b&c)'),
        parse_expression('b=>!c&a'),
        parse_expression('b^c'),
        parse_expression('a|c=>c^b'),
        parse_expression('(c^b)|(a&!b)'),
        parse_expression('!(b&c)'),
        parse_expression('!a&b&c'),
        parse_expression('(b<=>c)&!a'),
        parse_expression('(a^c)&(b<=>c)'),
        parse_expression('(b=>!a)&(b<=>c)'),
        parse_expression('!a&b'),
        parse_expression('!a&(c=>b)'),
        parse_expression('(a^b)&(c=>b)'),
        parse_expression('c|b=>!a&b'),
        parse_expression('b&(a^c)'),
        parse_expression('a^c<=>b|(a&c)'),
        parse_expression('(c^a)&(b|a)'),
        parse_expression('!((b=>a)<=>c)'),
        parse_expression('!(b=>a&c)'),
        parse_expression('(a=>!c&b)&(c=>b)'),
        parse_expression('!(a&c)&(b|a)'),
        parse_expression('c=>b&!a'),
        parse_expression('!a&c'),
        parse_expression('!a&(b>c)'),
        parse_expression('(b=>c)&(c^a)'),
        parse_expression('(b=>c)&!(c&a)'),
        parse_expression('!a&(b|c)'),
        parse_expression('!a'),
        parse_expression('a^(b|c)'),
        parse_expression('a>!(b|c)'),
        parse_expression('(a^c)&(a=>b)'),
        parse_expression('!((b=>c)<=>a)'),
        parse_expression('a^c'),
        parse_expression('b|c=>c^a'),
        parse_expression('!(a&c)&(c|b)'),
        parse_expression('a>!(b>c)'),
        parse_expression('(c^a)|(!a&b)'),
        parse_expression('!(a&c)'),
        parse_expression('(a^b)&c'),
        parse_expression('a^b=c|(a&b)'),
        parse_expression('(b^a)&(b=>c)'),
        parse_expression('!((c=>a)<=>b)'),
        parse_expression('(a^b)&(c|b)'),
        parse_expression('!((c=>b)<=>a)'),
        parse_expression('a^b'),
        parse_expression('b|c=>a^b'),
        parse_expression('((c&a)^b)&(c|a)'),
        parse_expression('!(a^b^c)'),
        parse_expression('a^(b&c)'),
        parse_expression('b|c=>(b&c)^a'),
        parse_expression('b^(a&c)'),
        parse_expression('a|c=>b^(a&c)'),
        parse_expression('(!c&b)|(b^a)'),
        parse_expression('c=>b^a'),
        parse_expression('c&!(b&a)'),
        parse_expression('a|b=>!(a&b)&c'),
        parse_expression('!(b&a)&(c|a)'),
        parse_expression('b=>!a&c'),
        parse_expression('(a=>!b)&(b|c)'),
        parse_expression('a=>!b&c'),
        parse_expression('(c&!b)|(b^a)'),
        parse_expression('!(a&b)'),
        parse_expression('c^(a&b)'),
        parse_expression('a|b=>(a&b)^c'),
        parse_expression('(!b&a)|(c^a)'),
        parse_expression('b=>a^c'),
        parse_expression('(b&!a)|(c^b)'),
        parse_expression('a=>c^b'),
        parse_expression('(c^a)|(a^b)'),
        parse_expression('!(a&b&c)'),
        parse_expression('a&b&c'),
        parse_expression('(c<=>b)&(a<=>b)'),
        parse_expression('(b<=>c)&a'),
        parse_expression('(b=>a)&(c<=>b)'),
        parse_expression('b&(a<=>c)'),
        parse_expression('(c=>b)&(a<=>c)'),
        parse_expression('(b&a<=>c)&(b|a)'),
        parse_expression('!(c^(a&b))'),
        parse_expression('a&b'),
        parse_expression('(c=>b)&(b<=>a)'),
        parse_expression('a&(c=>b)'),
        parse_expression('(c=>b)&(b=>a)'),
        parse_expression('b&(c=>a)'),
        parse_expression('c|a=>a&b'),
        parse_expression('(c=>a&b)&(a|b)'),
        parse_expression('c=>b&a'),
        parse_expression('c&(b<=>a)'),
        parse_expression('(a=>c)&(b<=>a)'),
        parse_expression('(c&a<=>b)&(c|a)'),
        parse_expression('!(b^(a&c))'),
        parse_expression('(c=>a)<=>b&(a=>c)'),
        parse_expression('!(a^(b&c))'),
        parse_expression('a^b^c'),
        parse_expression('b|c=>(b&c<=>a)'),
        parse_expression('(b<=>a)&(b|c)'),
        parse_expression('!(a^b)'),
        parse_expression('a<=>(c=>b)'),
        parse_expression('b|c=>(b<=>a)'),
        parse_expression('(c=>a)<=>b'),
        parse_expression('a|c=>(a<=>b)'),
        parse_expression('((b&a)|c)^b^a'),
        parse_expression('c=>(a<=>b)'),
        parse_expression('a&c'),
        parse_expression('(b=>c)&(c<=>a)'),
        parse_expression('a&(b>c)'),
        parse_expression('c|b=>c&a'),
        parse_expression('(c|b)&(a<=>c)'),
        parse_expression('!(a^c)'),
        parse_expression('a<=>(b=>c)'),
        parse_expression('c|b=>(c<=>a)'),
        parse_expression('a&(b|c)'),
        parse_expression('a<=>b|c'),
        parse_expression('a'),
        parse_expression('b|c=>a'),
        parse_expression('(c=>a)&(b|c)'),
        parse_expression('(a&b)|(a<=>c)'),
        parse_expression('a|(b&!c)'),
        parse_expression('c=>a'),
        parse_expression('c&(b=>a)'),
        parse_expression('a|b=>a&c'),
        parse_expression('(b=>a&c)&(a|c)'),
        parse_expression('b=>c&a'),
        parse_expression('(b=>a)<=>c'),
        parse_expression('a|b=>(c<=>a)'),
        parse_expression('(c=>b)&a<=>b<=>c'),
        parse_expression('b=>(c<=>a)'),
        parse_expression('(c|b)&(b=>a)'),
        parse_expression('(a&c)|(a<=>b)'),
        parse_expression('a|(!b&c)'),
        parse_expression('b=>a'),
        parse_expression('b<=>(c=>b&a)'),
        parse_expression('(a<=>c)|(b^c)'),
        parse_expression('a|(c^b)'),
        parse_expression('c&b=>a'),
        parse_expression('b&c'),
        parse_expression('(a=>c)&(c<=>b)'),
        parse_expression('(c|a)&(b<=>c)'),
        parse_expression('!(b^c)'),
        parse_expression('(a>c)&b'),
        parse_expression('a|c=>b&c'),
        parse_expression('b<=>(a=>c)'),
        parse_expression('c|a=>(c<=>b)'),
        parse_expression('(a|c)&b'),
        parse_expression('b<=>c|a'),
        parse_expression('(a|c)&(c=>b)'),
        parse_expression('(b&a)|(b<=>c)'),
        parse_expression('b'),
        parse_expression('a|c=>b'),
        parse_expression('(a&!c)|b'),
        parse_expression('c=>b'),
        parse_expression('(a>b)&c'),
        parse_expression('b|a=>b&c'),
        parse_expression('c<=>(a=>b)'),
        parse_expression('b|a=>(c<=>b)'),
        parse_expression('(a=>b&c)&(b|c)'),
        parse_expression('a=>b&c'),
        parse_expression('(b=>a)&c<=>b<=>a'),
        parse_expression('a=>(c<=>b)'),
        parse_expression('(a=>b)&(a|c)'),
        parse_expression('(b<=>a)|(c&b)'),
        parse_expression('a<=>(c=>a&b)'),
        parse_expression('(b<=>c)|(a^c)'),
        parse_expression('(!a&c)|b'),
        parse_expression('a>b'),
        parse_expression('(c^a)|b'),
        parse_expression('c=>(a=>b)'),
        parse_expression('(a|b)&c'),
        parse_expression('c<=>b|a'),
        parse_expression('(b|a)&(b=>c)'),
        parse_expression('(c&a)|(c<=>b)'),
        parse_expression('(a=>c)&(b|a)'),
        parse_expression('(c&b)|(c<=>a)'),
        parse_expression('a<=>(b=>c&a)'),
        parse_expression('(b^a)|(c<=>b)'),
        parse_expression('(a&(b|c))|(b&c)'),
        parse_expression('(a|b<=>c)|(a&b)'),
        parse_expression('a|(b&c)'),
        parse_expression('a|(c<=>b)'),
        parse_expression('(a&c)|b'),
        parse_expression('(a<=>c)|b'),
        parse_expression('a|b'),
        parse_expression('(c=>a)|b'),
        parse_expression('c'),
        parse_expression('a|b=>c'),
        parse_expression('(a&!b)|c'),
        parse_expression('b>c'),
        parse_expression('(!a&b)|c'),
        parse_expression('a>c'),
        parse_expression('c|(a^b)'),
        parse_expression('a>(b>c)'),
        parse_expression('(a&b)|c'),
        parse_expression('c|(a<=>b)'),
        parse_expression('a|c'),
        parse_expression('(b=>a)|c'),
        parse_expression('b|c'),
        parse_expression('a=>b|c'),
        parse_expression('a|b|c'),
        Constant(True)
    ]
]

def bool_array_to_int(arr):
    i = 0
    for e in reversed(arr):
        i <<= 1
        i += e
    return i

def eval_to_bool(expr, ids_to_symbols):
    dim = len(ids_to_symbols)
    return bool_array_to_int([expr.evaluate(symbol_dict_from_index(ids_to_symbols, BoolVector(dim, i))) for i in range(pow2(dim))])


def try_lookup_expression(expr):
    ids_to_symbols = gather_symbols_from_expr(expr)
    dim = len(ids_to_symbols)
    if dim > 3 or dim < 2:
        return expr

    if dim == 2:
        return expression_lookup_tables[dim][eval_to_bool(expr, ids_to_symbols)].substitute({'a' : Symbol(ids_to_symbols[0]), 'b' : Symbol(ids_to_symbols[1])})
    elif dim == 3:
        return expression_lookup_tables[dim][eval_to_bool(expr, ids_to_symbols)].substitute({'a' : Symbol(ids_to_symbols[0]), 'b' : Symbol(ids_to_symbols[1]), 'c' : Symbol(ids_to_symbols[2])})